FORMAT: 1A
host: https://arato-api.herokuapp.com

# arato
Notes API is a *short texts saving* service similar to its physical paper presence on your table.


# Group Authentication
Notes related resources of the **Authentication API**


# Group alerts
Notes related resources of the **Alerts API**

## Model

Below are all properties related to an Alert.

| Field        | Required for creation | Read only | type   | Description                                     |
|--------------|:---------------------:|:---------:|--------|-------------------------------------------------|
| `id`         |           ✔           |           | int    | The id in the database                          |
| `title`      |           ✔           |           | String | The title of the Alert                          |
| `price`      |           ✔           |           | int    | The price of the Alert                          |
| `content`    |                       |           | String | A more complete description of the Alert        |
| `user_id`    |           ✔           |     ✔     | int    | The id of the User who created the Alert        |
| `created_at` |                       |     ✔     | Date   | a ISO8601 formatted date.                       |
| `updated_at` |                       |     ✔     | Date   | a ISO8601 formatted date. Updated on each save. |


## api/v1/alerts [/api/v1/alerts{?page,limit,userId,sort,order}]

### Retrieve all alerts [GET]
+ Parameters
    + page (optional, number) ... The page
    + userId (optional, string) ... A user id to filter from
    + limit = `20` (optional, number) ... The number of elements per page. Maximum `50`.
    + sort  = `id` (optional, string) ... The field to sort from.
        + Values
            + `id`
            + `created_at`
            + `price`
    + order = `desc`(optional, string) ... The order of sorting.
        + Values
            + `asc`
            + `desc`

+ Response 200 (application/json)

        {
            "users":[
                {
                    "id":1,
                    "email":"email@example.com",
                    "sequence_number":0
                },
                {
                    "id":2,
                    "email":"email2@example.com",
                    "sequence_number":0
                }
            ],
            "paginate":{
                "total_count":2,
                "total_pages":1,
                "current_page":1,
                "limit":20
            }
        }

+ Response 401

### Create a new alert [POST]

+ Request (application/json)

        {
            "title": "My title",
            "price" : "10",
            "content" : "Hello"
        }


+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }


## api/v1/alerts/{id} [/api/v1/alerts/{id}]

### Update an alert [PUT]
+ Parameters
    + id (required, number) ... The id of the Alert.

+ Request (application/json)

        {
            "title": "My title",
            "price" : "10",
            "content" : "Hello"
        }

+ Response 200 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

### Delete an alert [DELETE]
+ Parameters
    + id (required, number) ... The id of the Alert.

+ Response 204 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

# Group Users
Notes related resources of the **Users API**